language: python
python:
  - 3.7
cache: pip

install:
  - pip install flake8 codecov pytest pytest-cov 


script:
  - python -m flake8 my_src/
  - python -m pytest -vvv my_src/tests/tests.py --cov my_src

after_success:
  - codecov
 
branches:
  only:
  - master