language: python
dist: xenial
python:
  - 3.8

os:
  - linux

before_deploy:
  - pip install travis-wait-improved

deploy:
  - provider: script
    script: travis-wait-improved --timeout 30m packer build packer.json

install:
  - pip install -U pip wheel
  - pip install flake8 codecov pytest pytest-cov
  - pip install -r requirements.txt

cache:
  directories:
    - $HOME/.cache/pip

script:
  - python -m flake8 my_src/
  - python -m pytest -vvv my_src/tests/tests.py --cov my_src

after_success:
  - codecov

branches:
  only:
    - master
