language: python

cache: pip
os:
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi

install:
  - pip install flake8 codecov pytest pytest-cov 
  - brew install portaudio
  - pip install pyaudio


script:
  - python -m flake8 my_src/
  - python -m pytest -vvv my_src/tests/tests.py --cov my_src

after_success:
  - codecov
 
branches:
  only:
  - master