language: python
dist: xenial
python:
  - 3.6
cache: pip
os:
  - linux

install:
  - pip install flake8 codecov pytest pytest-cov


script:
  - python -m flake8 my_src/
  - python -m pytest -vvv my_src/tests/tests.py --cov my_src

after_success:
  - codecov

branches:
  only:
    - master
